In [1]:
import numpy as np

### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrix_plus_eye = matrix + np.eye(3)
matrix_plus_eye

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [11]:
matrix_multiply_vector = matrix_plus_eye*np.array([1, 2, 3])
matrix_multiply_vector

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [12]:
matrix_transpose = np.linalg.matrix_transpose(matrix_multiply_vector)
matrix_transpose

array([[ 2.,  4.,  7.],
       [ 4., 12., 16.],
       [ 9., 18., 30.]])

In [14]:
matrix_inv = np.linalg.inv(matrix_transpose)
matrix_inv

array([[-6.        , -0.5       ,  1.66666667],
       [-2.        ,  0.25      ,  0.33333333],
       [ 3.        ,  0.        , -0.66666667]])

### Задание 2

Найдите собственные значения и собственные вектора матрицы:

In [46]:
m = np.array([[2, 2], [1, 3]])

res = np.linalg.eig(m)
res_transpose = np.linalg.matrix_transpose(res[1])
v1 = res_transpose[0] / res_transpose[0][0]
v2 = res_transpose[1] / res_transpose[1][0]
print(f"Eigen Values: {res[0]}")
print(f"Eigen Vectors: {v1}, {v2}")


Eigen Values: [1. 4.]
Eigen Vectors: [ 1.  -0.5], [1. 1.]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [61]:
matrix = np.tril(np.ones((5, 5)))
print(f"Matrix:\n{matrix}\nDeterminant: {np.linalg.det(matrix)}")

Matrix:
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
Determinant: 1.0
